const pizzaData = [
  {
    name: "Focaccia",
    ingredients: "Bread with italian olive oil and rosemary",
    price: 6,
    photoName: "pizzas/focaccia.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Margherita",
    ingredients: "Tomato and mozarella",
    price: 10,
    photoName: "pizzas/margherita.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Spinaci",
    ingredients: "Tomato, mozarella, spinach, and ricotta cheese",
    price: 12,
    photoName: "pizzas/spinaci.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Funghi",
    ingredients: "Tomato, mozarella, mushrooms, and onion",
    price: 12,
    photoName: "pizzas/funghi.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Salamino",
    ingredients: "Tomato, mozarella, and pepperoni",
    price: 15,
    photoName: "pizzas/salamino.jpg",
    soldOut: true,
    category: "meat",
  },
  {
    name: "Pizza Prosciutto",
    ingredients: "Tomato, mozarella, ham, aragula, and burrata cheese",
    price: 18,
    photoName: "pizzas/prosciutto.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Diavola",
    ingredients: "Spicy salami, chili peppers, mozarella, and tomato",
    price: 14,
    photoName: "pizzas/diavola.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Quattro Formaggi",
    ingredients: "Mozarella, gorgonzola, parmesan, and fontina cheese",
    price: 14,
    photoName: "pizzas/quattro.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Capricciosa",
    ingredients: "Ham, mushrooms, artichokes, olives, and mozarella",
    price: 15,
    photoName: "pizzas/capricciosa.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Tonno",
    ingredients: "Tuna, red onion, mozarella, and tomato",
    price: 14,
    photoName: "pizzas/tonno.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Parma",
    ingredients: "Parma ham, rucola, parmesan shavings, and cherry tomatoes",
    price: 17,
    photoName: "pizzas/parma.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Boscaiola",
    ingredients: "Mushrooms, italian sausage, mozarella, and rosemary",
    price: 13,
    photoName: "pizzas/boscaiola.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Ortolana",
    ingredients: "Grilled zucchini, eggplant, bell peppers, and cherry tomatoes",
    price: 11,
    photoName: "pizzas/ortolana.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Pizza Calzone",
    ingredients: "Folded pizza with ham, mozarella, ricotta, and tomato",
    price: 13,
    photoName: "pizzas/calzone.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Frutti di Mare",
    ingredients: "Shrimp, mussels, calamari, garlic, and white wine",
    price: 16,
    photoName: "pizzas/frutti.jpg",
    soldOut: false,
    category: "meat",
  },
  {
    name: "Pizza Bianca",
    ingredients: "Olive oil, mozarella, rosemary, and sea salt",
    price: 9,
    photoName: "pizzas/bianca.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Bruschetta",
    ingredients: "Toasted bread, fresh tomatoes, basil, and garlic",
    price: 5,
    photoName: "pizzas/bruschetta.jpg",
    soldOut: false,
    category: "vegetarian",
  },
  {
    name: "Garlic Bread",
    ingredients: "Crusty bread, garlic butter, parsley, and parmesan",
    price: 4,
    photoName: "pizzas/garlicbread.jpg",
    soldOut: false,
    category: "vegetarian",
  },
];

export default pizzaData;
